version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: aboud 
      POSTGRES_PASSWORD: ufc123 
      POSTGRES_DB: ufcdb 
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data # used to ensure that the data is persisted even if the container is removed

volumes:
  db-data:
